// src-react/components/LocationParser.tsx
/**
 * 地名解析组件
 * 提供地名解析的用户界面
 */

import React, { useState, useCallback } from 'react'
import type { LocationInput } from '../types/location'
import { useLocationParser, useLocationAutoComplete, useLocationHistory } from '../hooks/useLocationParser'

// 组件属性类型
interface LocationParserProps {
  onLocationParsed?: (result: any) => void
  onError?: (error: string) => void
  placeholder?: string
  className?: string
  showHistory?: boolean
  showBatchMode?: boolean
}

/**
 * 地名解析主组件
 */
export function LocationParser({
  onLocationParsed,
  onError,
  placeholder = '请输入地名，如：北京市朝阳区',
  className = '',
  showHistory = true,
  showBatchMode = true
}: LocationParserProps) {
  const [mode, setMode] = useState<'single' | 'batch'>('single')
  const [batchInput, setBatchInput] = useState('')
  
  // 使用地名解析 Hook
  const {
    isLoading,
    error,
    result,
    batchResult,
    parseLocation,
    parseBatch,
    retry
  } = useLocationParser()
  
  // 使用自动完成 Hook
  const {
    input,
    setInput,
    correctedInput,
    suggestions,
    selectSuggestion,
    clearInput
  } = useLocationAutoComplete()
  
  // 使用历史记录 Hook
  const { history, addToHistory, clearHistory } = useLocationHistory()
  
  // 处理单个地名解析
  const handleSingleParse = useCallback(async () => {
    if (!input.trim()) return
    
    const locationInput: LocationInput = {
      name: correctedInput || input,
      timeout: 5000,
      useCache: true
    }
    
    await parseLocation(locationInput)
  }, [input, correctedInput, parseLocation])
  
  // 处理批量地名解析
  const handleBatchParse = useCallback(async () => {
    if (!batchInput.trim()) return
    
    await parseBatch(batchInput)
  }, [batchInput, parseBatch])
  
  // 处理解析结果
  React.useEffect(() => {
    if (result?.success && result.location) {
      addToHistory(result.location)
      onLocationParsed?.(result)
    }
    
    if (batchResult && batchResult.summary && batchResult.summary.successful > 0) {
      // 将成功解析的地名添加到历史记录
      batchResult.results.forEach(item => {
        if (item.success && item.location) {
          addToHistory(item.location)
        }
      })
      onLocationParsed?.(batchResult)
    }
  }, [result, batchResult, addToHistory, onLocationParsed])
  
  // 处理错误
  React.useEffect(() => {
    if (error) {
      onError?.(error)
    }
  }, [error, onError])
  
  return (
    <div className={`location-parser ${className}`}>
      {/* 模式切换 */}
      {showBatchMode && (
        <div className="mode-switcher">
          <button
            className={`mode-btn ${mode === 'single' ? 'active' : ''}`}
            onClick={() => setMode('single')}
          >
            单个解析
          </button>
          <button
            className={`mode-btn ${mode === 'batch' ? 'active' : ''}`}
            onClick={() => setMode('batch')}
          >
            批量解析
          </button>
        </div>
      )}
      
      {/* 单个地名解析 */}
      {mode === 'single' && (
        <div className="single-mode">
          <div className="input-container">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder={placeholder}
              className="location-input"
              onKeyPress={(e) => e.key === 'Enter' && handleSingleParse()}
            />
            
            {/* 输入建议 */}
            {suggestions.length > 0 && (
              <div className="suggestions">
                {suggestions.map((suggestion, index) => (
                  <div
                    key={index}
                    className="suggestion-item"
                    onClick={() => selectSuggestion(suggestion)}
                  >
                    {suggestion}
                  </div>
                ))}
              </div>
            )}
          </div>
          
          {/* 输入修正提示 */}
          {correctedInput && correctedInput !== input && (
            <div className="correction-hint">
              建议修正为: <span className="corrected-text">{correctedInput}</span>
            </div>
          )}
          
          <div className="action-buttons">
            <button
              onClick={handleSingleParse}
              disabled={isLoading || !input.trim()}
              className="parse-btn primary"
            >
              {isLoading ? '解析中...' : '解析地名'}
            </button>
            
            <button
              onClick={clearInput}
              className="clear-btn"
            >
              清空
            </button>
          </div>
        </div>
      )}
      
      {/* 批量地名解析 */}
      {mode === 'batch' && (
        <div className="batch-mode">
          <textarea
            value={batchInput}
            onChange={(e) => setBatchInput(e.target.value)}
            placeholder="请输入多个地名，每行一个：&#10;北京市朝阳区&#10;上海市浦东新区&#10;广州市天河区"
            className="batch-input"
            rows={6}
          />
          
          <div className="action-buttons">
            <button
              onClick={handleBatchParse}
              disabled={isLoading || !batchInput.trim()}
              className="parse-btn primary"
            >
              {isLoading ? '批量解析中...' : '批量解析'}
            </button>
            
            <button
              onClick={() => setBatchInput('')}
              className="clear-btn"
            >
              清空
            </button>
          </div>
        </div>
      )}
      
      {/* 错误显示 */}
      {error && (
        <div className="error-message">
          <span className="error-text">{error}</span>
          <button onClick={retry} className="retry-btn">
            重试
          </button>
        </div>
      )}
      
      {/* 解析结果 */}
      {result?.success && result.location && (
        <LocationResult location={result.location} />
      )}
      
      {/* 批量解析结果 */}
      {batchResult && (
        <BatchLocationResult result={batchResult} />
      )}
      
      {/* 历史记录 */}
      {showHistory && history.length > 0 && (
        <LocationHistory
          history={history}
          onClearHistory={clearHistory}
          onSelectLocation={(location) => {
            setInput(location.name)
            setMode('single')
          }}
        />
      )}
    </div>
  )
}

/**
 * 单个地名解析结果组件
 */
function LocationResult({ location }: { location: any }) {
  return (
    <div className="location-result">
      <h3>解析结果</h3>
      <div className="result-content">
        <div className="location-info">
          <div className="location-name">{location.name}</div>
          <div className="location-address">{location.address}</div>
          <div className="location-coords">
            经度: {location.coordinate.longitude.toFixed(6)}, 
            纬度: {location.coordinate.latitude.toFixed(6)}
          </div>
          {location.level && (
            <div className="location-level">级别: {location.level}</div>
          )}
        </div>
        
        {location.district && (
          <div className="district-info">
            <h4>行政区划</h4>
            <div>省份: {location.district.province}</div>
            <div>城市: {location.district.city}</div>
            <div>区县: {location.district.district}</div>
          </div>
        )}
      </div>
    </div>
  )
}

/**
 * 批量解析结果组件
 */
function BatchLocationResult({ result }: { result: any }) {
  const successCount = result.results.filter((r: any) => r.success).length
  const totalCount = result.results.length
  
  return (
    <div className="batch-result">
      <h3>批量解析结果</h3>
      <div className="result-summary">
        成功: {successCount} / {totalCount}
      </div>
      
      <div className="result-list">
        {result.results.map((item: any, index: number) => (
          <div key={index} className={`result-item ${item.success ? 'success' : 'error'}`}>
            <div className="query-text">{item.query}</div>
            {item.success ? (
              <div className="location-brief">
                {item.data.name} - {item.data.coordinate.longitude.toFixed(4)}, {item.data.coordinate.latitude.toFixed(4)}
              </div>
            ) : (
              <div className="error-text">{item.error?.message}</div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}

/**
 * 历史记录组件
 */
function LocationHistory({ 
  history, 
  onClearHistory, 
  onSelectLocation 
}: { 
  history: any[]
  onClearHistory: () => void
  onSelectLocation: (location: any) => void
}) {
  return (
    <div className="location-history">
      <div className="history-header">
        <h3>解析历史</h3>
        <button onClick={onClearHistory} className="clear-history-btn">
          清空历史
        </button>
      </div>
      
      <div className="history-list">
        {history.map((location, index) => (
          <div
            key={index}
            className="history-item"
            onClick={() => onSelectLocation(location)}
          >
            <div className="history-name">{location.name}</div>
            <div className="history-coords">
              {location.coordinate.longitude.toFixed(4)}, {location.coordinate.latitude.toFixed(4)}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default LocationParser

// src/components/LocationParser.vue
<template>
  <div class="location-parser" :class="className">
    <!-- 模式切换 -->
    <div v-if="showBatchMode" class="mode-switcher">
      <button 
        :class="{ active: mode === 'single' }"
        @click="mode = 'single'"
      >
        单个解析
      </button>
      <button 
        :class="{ active: mode === 'batch' }"
        @click="mode = 'batch'"
      >
        批量解析
      </button>
    </div>

    <!-- 单个地名解析 -->
    <div v-if="mode === 'single'" class="single-mode">
      <div class="input-container">
        <input
          v-model="input"
          type="text"
          :placeholder="placeholder"
          class="location-input"
          @keyup.enter="handleSingleParse"
          :disabled="isLoading"
        />
        <button 
          @click="handleSingleParse"
          :disabled="!input.trim() || isLoading"
          class="parse-button"
        >
          {{ isLoading ? '解析中...' : '解析' }}
        </button>
      </div>

      <!-- 自动完成建议 -->
      <div v-if="suggestions.length > 0" class="suggestions">
        <div 
          v-for="suggestion in suggestions" 
          :key="suggestion.id"
          class="suggestion-item"
          @click="selectSuggestion(suggestion)"
        >
          {{ suggestion.name }}
        </div>
      </div>

      <!-- 输入纠正提示 -->
      <div v-if="correctedInput && correctedInput !== input" class="correction-hint">
        建议输入: {{ correctedInput }}
        <button @click="input = correctedInput" class="apply-correction">
          应用
        </button>
      </div>
    </div>

    <!-- 批量地名解析 -->
    <div v-if="mode === 'batch'" class="batch-mode">
      <div class="batch-input-container">
        <textarea
          v-model="batchInput"
          placeholder="请输入多个地名，支持以下格式：&#10;1. 逗号分隔：北京,上海,广州&#10;2. 换行分隔：&#10;   北京&#10;   上海&#10;   广州&#10;3. 箭头连接：北京→上海→广州"
          class="batch-input"
          rows="6"
          :disabled="isLoading"
        ></textarea>
        <button 
          @click="handleBatchParse"
          :disabled="!batchInput.trim() || isLoading"
          class="parse-button batch-parse-button"
        >
          {{ isLoading ? '批量解析中...' : '批量解析' }}
        </button>
      </div>
    </div>

    <!-- 错误显示 -->
    <div v-if="error" class="error-message">
      <span>{{ error }}</span>
      <button @click="retry" class="retry-button">重试</button>
    </div>

    <!-- 单个解析结果 -->
    <LocationResult 
      v-if="result?.success && result.location" 
      :location="result.location" 
    />

    <!-- 批量解析结果 -->
    <BatchLocationResult 
      v-if="batchResult && batchResult.summary" 
      :result="batchResult" 
    />

    <!-- 历史记录 -->
    <LocationHistory
      v-if="showHistory && history.length > 0"
      :history="history"
      @clear-history="clearHistory"
      @select-location="handleHistorySelect"
    />
  </div>
</template>

<script setup lang="ts">
/**
 * 地名解析组件 - Vue 3版本
 */

import { ref, computed, watch } from 'vue'
import type { LocationInput } from '../types/location'
import { useLocationParser } from '../composables/useLocationParser'
import { useLocationAutoComplete } from '../composables/useLocationAutoComplete'
import { useLocationHistory } from '../composables/useLocationHistory'
import LocationResult from './LocationResult.vue'
import BatchLocationResult from './BatchLocationResult.vue'
import LocationHistory from './LocationHistory.vue'

// 组件属性
interface Props {
  placeholder?: string
  className?: string
  showHistory?: boolean
  showBatchMode?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: '请输入地名，如：北京市朝阳区',
  className: '',
  showHistory: true,
  showBatchMode: true
})

// 组件事件
const emit = defineEmits<{
  locationParsed: [result: any]
  error: [error: string]
}>()

// 响应式数据
const mode = ref<'single' | 'batch'>('single')
const batchInput = ref('')

// 使用组合式函数
const {
  isLoading,
  error,
  result,
  batchResult,
  parseLocation,
  parseBatch,
  retry
} = useLocationParser()

const {
  input,
  correctedInput,
  suggestions,
  selectSuggestion,
  clearInput
} = useLocationAutoComplete()

const { history, addToHistory, clearHistory } = useLocationHistory()

// 处理单个地名解析
const handleSingleParse = async () => {
  if (!input.value.trim()) return
  
  const locationInput: LocationInput = {
    name: correctedInput.value || input.value,
    timeout: 5000,
    useCache: true
  }
  
  await parseLocation(locationInput)
}

// 处理批量地名解析
const handleBatchParse = async () => {
  if (!batchInput.value.trim()) return
  
  await parseBatch(batchInput.value)
}

// 处理历史记录选择
const handleHistorySelect = (location: any) => {
  input.value = location.name
}

// 监听解析结果
watch(result, (newResult) => {
  if (newResult?.success && newResult.location) {
    addToHistory(newResult.location)
    emit('locationParsed', newResult)
  }
})

watch(batchResult, (newBatchResult) => {
  if (newBatchResult && newBatchResult.summary && newBatchResult.summary.successful > 0) {
    // 将成功解析的地名添加到历史记录
    newBatchResult.results.forEach((item: any) => {
      if (item.success && item.location) {
        addToHistory(item.location)
      }
    })
    emit('locationParsed', newBatchResult)
  }
})

// 监听错误
watch(error, (newError) => {
  if (newError) {
    emit('error', newError)
  }
})
</script>

<style scoped>
.location-parser {
  max-width: 800px;
  margin: 0 auto;
  padding: 1rem;
}

.mode-switcher {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  justify-content: center;
}

.mode-switcher button {
  padding: 0.5rem 1rem;
  border: 2px solid #667eea;
  background: white;
  color: #667eea;
  border-radius: 0.5rem;
  cursor: pointer;
  transition: all 0.2s;
}

.mode-switcher button.active,
.mode-switcher button:hover {
  background: #667eea;
  color: white;
}

.input-container {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.location-input {
  flex: 1;
  padding: 0.75rem;
  border: 2px solid #e0e0e0;
  border-radius: 0.5rem;
  font-size: 1rem;
  transition: border-color 0.2s;
}

.location-input:focus {
  outline: none;
  border-color: #667eea;
}

.parse-button {
  padding: 0.75rem 1.5rem;
  background: #667eea;
  color: white;
  border: none;
  border-radius: 0.5rem;
  cursor: pointer;
  font-size: 1rem;
  transition: background-color 0.2s;
}

.parse-button:hover:not(:disabled) {
  background: #5a6fd8;
}

.parse-button:disabled {
  background: #ccc;
  cursor: not-allowed;
}

.batch-input-container {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.batch-input {
  width: 100%;
  padding: 0.75rem;
  border: 2px solid #e0e0e0;
  border-radius: 0.5rem;
  font-size: 1rem;
  font-family: inherit;
  resize: vertical;
  transition: border-color 0.2s;
}

.batch-input:focus {
  outline: none;
  border-color: #667eea;
}

.batch-parse-button {
  align-self: flex-end;
}

.suggestions {
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 0.5rem;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  margin-bottom: 1rem;
}

.suggestion-item {
  padding: 0.75rem;
  cursor: pointer;
  border-bottom: 1px solid #f0f0f0;
  transition: background-color 0.2s;
}

.suggestion-item:hover {
  background: #f8f9ff;
}

.suggestion-item:last-child {
  border-bottom: none;
}

.correction-hint {
  background: #fff3cd;
  border: 1px solid #ffeaa7;
  border-radius: 0.5rem;
  padding: 0.75rem;
  margin-bottom: 1rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.apply-correction {
  padding: 0.25rem 0.5rem;
  background: #667eea;
  color: white;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
  font-size: 0.875rem;
}

.error-message {
  background: #f8d7da;
  border: 1px solid #f5c6cb;
  border-radius: 0.5rem;
  padding: 0.75rem;
  margin-bottom: 1rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  color: #721c24;
}

.retry-button {
  padding: 0.25rem 0.5rem;
  background: #dc3545;
  color: white;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
  font-size: 0.875rem;
}
</style>
